WARNING  Allure Section:_allure_section.py:106 Caught exception: Failed exception here